//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was incorrect.
        /// </summary>
        public static string IncorrectPasswordMessage {
            get {
                return ResourceManager.GetString("IncorrectPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string IncorrectPasswordTitle {
            get {
                return ResourceManager.GetString("IncorrectPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There does not exist a user with the given name.
        /// </summary>
        public static string IncorrectUserNameMessage {
            get {
                return ResourceManager.GetString("IncorrectUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username.
        /// </summary>
        public static string IncorrectUserNameTitle {
            get {
                return ResourceManager.GetString("IncorrectUserNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asegurate de que las contraseñas sean iguales.
        /// </summary>
        public static string PasswordsDontMatchMessage {
            get {
                return ResourceManager.GetString("PasswordsDontMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no son iguales.
        /// </summary>
        public static string PasswordsDontMatchTitle {
            get {
                return ResourceManager.GetString("PasswordsDontMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener por lo menos cinco caracteres.
        /// </summary>
        public static string PasswordTooShortMessage {
            get {
                return ResourceManager.GetString("PasswordTooShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña muy corta.
        /// </summary>
        public static string PasswordTooShortTitle {
            get {
                return ResourceManager.GetString("PasswordTooShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado un correo de confirmacion :).
        /// </summary>
        public static string RegistrationSuccessfulMessage {
            get {
                return ResourceManager.GetString("RegistrationSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro completado.
        /// </summary>
        public static string RegistrationSuccessfulTitle {
            get {
                return ResourceManager.GetString("RegistrationSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No debe contener espacios ni caracteres especiales..
        /// </summary>
        public static string ShouldNotHaveSpacesOrSpecialCharacters {
            get {
                return ResourceManager.GetString("ShouldNotHaveSpacesOrSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre ya esta uso, intenta con otro :(.
        /// </summary>
        public static string UserNameAlreadyInUseMessage {
            get {
                return ResourceManager.GetString("UserNameAlreadyInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario ya esta en uso.
        /// </summary>
        public static string UserNameAlreadyInUseTitle {
            get {
                return ResourceManager.GetString("UserNameAlreadyInUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre tener al menos tres caracteres.
        /// </summary>
        public static string UserNameTooShortMessage {
            get {
                return ResourceManager.GetString("UserNameTooShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre demasiado corto.
        /// </summary>
        public static string UserNameTooShortTitle {
            get {
                return ResourceManager.GetString("UserNameTooShortTitle", resourceCulture);
            }
        }
    }
}
